### ISSUE TITLE
about the PNG generating

### ISSUE THREAD

**Issue by harveyaot** [wayou/t-rex-runner#17]
Thanks for sharing this interesting project.

I would like to adapt this to make a gift for my friend's birthday.

Could you please share some lights on which tools you used to generate different version  PNG?
 
I will add more Letters, but don't know which tools to use ,and how to determine the letter's boundary.

Thanks. Any knowledge would be  appreciated!

**Comment by wayou** [comment]
I use QuickTime to record screen and https://github.com/mortenjust/droptogif to make gif.
