### ISSUE TITLE
Update to the latest game version

### ISSUE THREAD

**Issue by ngyikp** [wayou/t-rex-runner#2]
Chrome updated the game, added pterodactyls and fixed a few bugs, such as floating after jumping and quickly making the window inactive (GIF below), perhaps this repo needs an update?

![trex](https://cloud.githubusercontent.com/assets/6135313/10624103/fba70dd8-77c7-11e5-9705-a9e2a59e2a0e.gif)

**Comment by termonaitor2004** [comment]
try to get it to switch to night like the real one please
