### ISSUE TITLE
Safari Mobile Browser- Game Over View Not Rendered

### ISSUE THREAD

**Issue by ritesh-nitw** [wayou/t-rex-runner#3]
For some reason, the game over view is not loaded in safari mobile/ipad browser. The runner stick with cactus on collision, and the game over view/canvas never appear.

Works fine in android mobile browser, and safari "pc web browser" as well. Tested on my ipad safari browser, all works well expect game over view. 
So I have to reload the page every time.

**Comment by wayou** [comment]
i get no ios devices, so i've no idea what's going on.
i updated the game to the latest version from chromium, hope that may fix this issue.

**Comment by wayou** [comment]
never mind about ios
