### ISSUE TITLE
Isn't it confusing having both "achievments" and "acheivments" as variables?

### ISSUE THREAD

**Issue by edo9k** [wayou/t-rex-runner#37]
So it in this line, what is the difference between an achievment (ach-IE-vment)and an acheivment (ach-EI-vment) in this code?

https://github.com/wayou/t-rex-runner/blob/e67b69603ef7fae7a52afe215fc4ed645a61013e/index.js#L1870

**Comment by DamieFC** [comment]
Huh. I don't know. Maybe it's a bug in the code, that wasn't found. Interesting observation though!

**Comment by kevinc21720** [comment]
`## Interesting Forks/In Chinese, we call it 「花样玩法」

- [vianroyal](https://github.com/vianroyal)/[t-rex-runner](https://github.com/vianroyal/t-rex-runner) [Kumamon runner](http://vianroyal.github.io/t-rex-runner/) 
<br>

![](assets/kumamon-runner.gif)

- [xkuga](https://github.com/xkuga)/[t-rex-runner](https://github.com/xkuga/t-rex-runner) [Hello KuGou](http://hellokugou.com/) 
<br>

![](assets/hello-kugou.gif)

- [d-nery](https://github.com/d-nery/)/[t-rex-runner](https://github.com/d-nery/t-rex-runner) [Novas coisas](http://d-nery.github.io/t-rex-runner/) 
<br>

![](assets/novas-coisas.gif)

- [chirag64](https://github.com/chirag64)/[t-rex-runner-bot](https://github.com/chirag64/t-rex-runner-bot) [t-rex runner bot](https://chirag64.github.io/t-rex-runner-bot/) 
<br>

![](assets/t-rex-runner-bot.gif)

- [19janil](https://github.com/19janil)/[t-rex-runner](https://github.com/19janil/t-rex-runner) [t-rex runner](https://19janil.github.io/t-rex-runner/) 
<br>

![](assets/t-rex-runner-19janil.gif)

- [enthus1ast](https://github.com/enthus1ast)/[chromeTrip](https://github.com/enthus1ast/chromeTrip) [Chrome Trip by code0](https://code0.itch.io/chrome-trip) 
<br>

![](https://user-images.githubusercontent.com/13794470/37289691-964618be-260a-11e8-8c4a-6df04d6c490d.gif)

- [zouariste](https://github.com/zouariste)/[corona-runner](https://github.com/zouariste/corona-runner) [Corona runner](https://dealsium.com/) 
<br>
![](assets/corona-runner.gif)
`

**Comment by Dear-koma** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
