### ISSUE TITLE
not opening in ie

### ISSUE THREAD

**Issue by ivansempijja** [wayou/t-rex-runner#7]
the game completely fails to open in ie.
var keyframes = '@-webkit-keyframes intro { ' +
            'from { width:' + Trex.config.WIDTH + 'px }' +
            'to { width: ' + this.dimensions.WIDTH + 'px }' +
          '}';
      document.styleSheets[0].insertRule(keyframes, 0); // error is here maybe

**Comment by wayou** [comment]
never mind about ie
