### ISSUE TITLE
[Not Updated] T-rex-runner Game from Chromium

### ISSUE THREAD

**Issue by ghost** [wayou/t-rex-runner#8]
Chromium got an update for the game, now it has a "Dark" mode type thing.
If i get to like score 700, it goes dark then at like 900 it comes back.

**Comment by ghost** [comment]
Proof: https://i.latouth.com/2016/d1J4CMb5

**Comment by Charles-IV** [comment]
It still doesn't go dark for me, I have no idea why, looking at the js files, the bits to do with night mode seem to be the same.
